import type { GeneratedPost } from "./types";

/**
 * Regenerated by `npm run generate-blog`. Do not edit by hand.
 * Consumed by lib/blog/posts.ts → blogSitemapPaths() → app/sitemap.ts
 */
export const generatedPosts: GeneratedPost[] = [];
