import type { GeneratedPost } from "./types";
import post_eliminating_per_seat_costs_with_wakeup_devs_unlimited_seat_on_call from "../../content/blog/eliminating-per-seat-costs-with-wakeup-devs-unlimited-seat-on-call.json";
import post_reducing_alert_fatigue_voice_ack_grafana_webhooks from "../../content/blog/reducing-alert-fatigue-voice-ack-grafana-webhooks.json";
import post_uptimerobot_webhooks_to_wakeup_dev_zero_downtime_alerting from "../../content/blog/uptimerobot-webhooks-to-wakeup-dev-zero-downtime-alerting.json";

/** Regenerated by `generate-post.mjs`. Do not edit by hand. */
export const generatedPosts: GeneratedPost[] = [
  post_eliminating_per_seat_costs_with_wakeup_devs_unlimited_seat_on_call as GeneratedPost,
  post_reducing_alert_fatigue_voice_ack_grafana_webhooks as GeneratedPost,
  post_uptimerobot_webhooks_to_wakeup_dev_zero_downtime_alerting as GeneratedPost,
];
